# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
pip install mdutils

In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda/envs/test3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/anaconda/envs/test3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda/envs/test3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
print("%d bytes" % (null.size*null.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
%run python -c "import numpy; http://numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
revA = A[::-1]
print(revA)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
B = np.arange(9).reshape(3,3)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
C = np.nonzero([1,2,0,0,4,0])
print(C)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
D = np.eye(3,3)
print(D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
E = np.random.random((3,3,3))
print(E)

[[[0.88955393 0.98112763 0.46640694]
  [0.0579536  0.73861599 0.41378595]
  [0.32624121 0.82390778 0.57127886]]

 [[0.51582513 0.72181427 0.30160183]
  [0.47112808 0.21488492 0.42788323]
  [0.52347864 0.44673036 0.71306405]]

 [[0.83378212 0.39816917 0.1342307 ]
  [0.48785532 0.1660874  0.73683994]
  [0.28179303 0.84379035 0.78937268]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
F = np.random.random((10,10))
print("Minimum: ", F.min())
print("Maximum: ", F.max())

Minimum:  0.009520292609272674
Maximum:  0.9959038892108142


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
G = np.random.random((30))
print("Mean Value: ", G.mean())

Mean Value:  0.5404396263808025


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
H = np.ones((3,3))
H[1:-1, 1:-1] = 0
print(H)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
H = np.pad(H, pad_width=1, mode='constant', constant_values=0)
print(H)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
I = np.diag(1+np.arange(4), k=-1)
print(I)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
J = np.zeros((8,8),dtype=int)
J[1::2,::2] = 1
J[::2,1::2] = 1
print(J)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [23]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
K = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(K)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
L = np.random.random((5,5))
normal = (L-np.mean(L)) / (np.std(L))
print(normal)

[[ 1.13778282 -0.70827067  0.06760223 -0.62703166  0.93941535]
 [ 1.56049203 -1.14490728 -0.96309582 -0.95953784  1.95886235]
 [ 0.20738374 -1.20366983  0.90856391  0.87263304  0.05733884]
 [-1.48357459  0.95218281 -1.39065995 -1.35269869  0.07898545]
 [ 0.60931897  1.32125095 -0.00665355 -0.60241605 -0.22929656]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [28]:
color = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
M = np.dot(np.ones((5,3)), np.ones((3,2)))
print(M)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [35]:
N = np.arange(11)
N[ (3<N) & (N<8) ] *= -1
print(N)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [36]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [41]:
Z=np.ones((3,3))
print(Z**Z) #legal

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
print(2 << Z >> 2)

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [43]:
print(Z <- Z) #legal

[[False False False]
 [False False False]
 [False False False]]


In [44]:
print(1j*Z) #legal

[[0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j]]


In [45]:
print(Z/1/1) #legal

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [46]:
print(Z<Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\anaconda\envs\test3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\anaconda\envs\test3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [49]:
O = np.random.uniform(-10,+10,10)

print(np.copysign(np.ceil(np.abs(O)), O))

[ -6.  -6.   3.   9.   4. -10.  -6.  -1.  -1.  -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [53]:
P1 = np.random.randint(0,10,10)
P2 = np.random.randint(0,10,10)
print(np.intersect1d(P1,P2))

[0 2 4 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [54]:
defaults = np.seterr(all="ignore")
Q = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [55]:
np.sqrt(-1) == np.emath.sqrt(-1) #False

C:\anaconda\envs\test3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [59]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2021-03-17
2021-03-18
2021-03-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [63]:
R = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(R)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [65]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
print(np.multiply(A,B))

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [69]:
S = np.random.uniform(0,10,10)

print(S.astype(int))
print(S - S%1)
print(S//1)
print(np.trunc(S))

[6 3 0 5 3 1 9 2 5 7]
[6. 3. 0. 5. 3. 1. 9. 2. 5. 7.]
[6. 3. 0. 5. 3. 1. 9. 2. 5. 7.]
[6. 3. 0. 5. 3. 1. 9. 2. 5. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [70]:
T = np.zeros((5,5))
T += np.arange(5)
print(T)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [81]:
def generator():
    for n in range(15):
        yield n
U = np.fromiter(generator(), dtype=float, count=-1)
print("New array:")
print(U)

New array:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [83]:
V = np.linspace(0,1,11, endpoint=False)[1:]
print(V)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [85]:
W = np.random.random(10)
W.sort()
print(W)

[0.5584296  0.61552445 0.61715017 0.63253334 0.64167466 0.88979863
 0.95315703 0.99116861 0.99556807 0.9996095 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [90]:
import timeit

x = range(10)

def pure_sum():
    return sum(x)

def numpy_sum():
    return np.sum(x)

n = 10

t1 = timeit.timeit(pure_sum, number = n)
print('Pure Python Sum:', t1)
t2 = timeit.timeit(numpy_sum, number = n)
print('Numpy Sum:', t2)

Pure Python Sum: 0.0002090000002681336
Numpy Sum: 0.00012800000013157842


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [91]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [95]:
Y = np.zeros(10)
Y.flags.writeable = False
Y[0] = 1 #False b/c it's read-only

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [97]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1] #cartesian coordinates

#polar coordinates
r = np.sqrt(X**2+Y**2)
t = np.arctan2(Y,X)
print(r)
print(t)

[0.52876165 0.76571798 0.3440532  0.78717041 0.75241364 0.46443636
 0.15386324 0.50034923 0.78066439 0.71660423]
[0.61278737 0.28355119 1.31721709 1.23009356 0.30895321 0.86647182
 0.17920324 0.53640291 1.1402757  0.34880996]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [99]:
AA = np.random.random(10)
AA[AA.argmax()] = 0 #maximum value=0
print(AA)

[0.60039572 0.31895738 0.         0.63321949 0.3610798  0.6650984
 0.07804473 0.63399538 0.31730633 0.17490917]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [100]:
BB = np.zeros((5,5), [('x',float),('y',float)])
BB['x'], BB['y'] = np.meshgrid(np.linspace(0,1,5),
                               np.linspace(0,1,5))
print(BB)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [102]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) #Cauchy
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [103]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [104]:
np.set_printoptions(threshold=float("inf"))
CC = np.zeros((10,10))
print(CC)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [105]:
DD = np.arange(100)
rand = np.random.uniform(0,100)
index = (np.abs(DD-rand)).argmin()
print(DD[index])

63


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [107]:
EE = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(EE)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [109]:
FF = np.random.random((100,2))
X,Y = np.atleast_2d(FF[:,0], FF[:,1])
dist = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(dist)

[[0.         0.91854126 0.44995083 0.43690496 0.53557062 0.8089086
  0.26371791 0.50149768 0.48143974 0.27536152 0.94079421 0.55587673
  0.12572354 0.14916603 0.87482577 0.83404339 0.62458091 0.99277894
  0.46138186 0.69389721 0.62048006 0.73102603 0.99089598 0.01899664
  0.47857725 0.87209275 0.73736255 0.47852969 0.95982844 0.949522
  0.84013565 0.237863   0.71316254 0.96184572 0.44410298 0.7686839
  0.52506073 0.44510861 0.18455109 0.48331246 0.76920867 0.603923
  0.42434667 0.07473332 0.39638668 0.79487484 0.79685475 0.17861037
  0.62781959 0.5063502  0.94798491 0.71747491 0.22745595 0.87924405
  0.19043443 0.63890733 0.3401459  0.08542128 0.9677003  0.65457805
  0.79748203 0.5597721  0.25851529 0.04025251 0.6582398  0.05696231
  0.44790438 0.63455942 0.62989905 0.80393708 0.67132107 0.06409746
  0.4842931  1.12365258 0.22957671 0.62721207 0.51719004 0.6354869
  0.25107651 0.23196116 0.86181871 0.86127632 0.17192532 0.5449139
  0.77426494 0.81591414 0.90621223 0.82990998 0.477394  

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [110]:
G = (np.random.rand(10)*100).astype(np.float32)
GG = G.view(np.int32)
GG[:] = G
print(GG)

[48 20  1 10 21 46 12 35 51 75]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [111]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
HH = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(HH)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [113]:
II = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(II):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [116]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
sigma, mu = (1.0, 0.0)
Gaussian = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(Gaussian)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [121]:
n = 5
p = 3
out = np.zeros((n,n),dtype=bool)
np.put(out,np.random.choice(range(n*n), p, replace=False),1)
print(out)

[[False False False False False]
 [ True False False False False]
 [False False False False False]
 [ True False False False False]
 [False False False False  True]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [122]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.22912809  0.29042889  0.23488493  0.46221904 -0.13732101 -0.13707458
  -0.04228463 -0.45018358 -0.01939715 -0.4304    ]
 [-0.03698973 -0.11223178 -0.29723432  0.48031381 -0.30312297  0.07384592
   0.0349981   0.02515311 -0.07757645  0.2128443 ]
 [-0.04524787  0.30987995 -0.12940049  0.02014424  0.13105117 -0.35837574
  -0.17263158  0.4108267  -0.18361852  0.01737213]
 [-0.30744895  0.32515614  0.12169629  0.3134796  -0.19528196 -0.09636294
  -0.24450892 -0.34056596  0.45926822 -0.03543152]
 [-0.21719634  0.19320923  0.28517109  0.28977779 -0.04063178 -0.12799435
  -0.11810656  0.01952228  0.30193847 -0.58568983]]


#### 59. How to sort an array by the nth column? (★★☆)

In [123]:
JJ = np.random.randint(0,10,(3,3))
print(JJ[JJ[:,1].argsort()]) #1th column sort

[[0 0 5]
 [5 4 3]
 [5 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [124]:
KK = np.random.randint(0,3,(3,10))

print((~KK.any(axis=0)).any()) #KK has null column

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [125]:
Z = np.random.uniform(0,1,10)
z = 0.5

LL = Z.flat[np.abs(Z - z).argmin()]
print(LL)

0.5052663766905205


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [126]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

MM = np.nditer([A,B,None])
for x,y,z in MM: 
    z[...] = x + y
print(MM.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [128]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [129]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 6. 3. 3. 3. 3. 3. 2. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [130]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [131]:
w = 256
h = 256
I = np.random.randint(0, 4, (w, h, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
num = len(colors)
print(num)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [132]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

[[62 54 44 74]
 [41 70 66 63]
 [57 54 63 69]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [133]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sum = np.bincount(S, weights=D)
D_count = np.bincount(S)
D_mean = D_sum / D_count
print(D_mean)

[0.52887457 0.62078144 0.52496113 0.52517822 0.50669445 0.53260253
 0.46096442 0.50142084 0.40550489 0.62887479]


#### 69. How to get the diagonal of a dot product? (★★★)

In [134]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.42702726, 1.30717856, 1.21652205, 1.9493525 , 0.82901742])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [135]:
MM = np.array([1,2,3,4,5])
newMM = 3
MM0 = np.zeros(len(MM) + (len(MM)-1)*(newMM))
MM0[::newMM+1] = MM
print(MM0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [136]:
M = np.ones((5,5,3))
N = 2*np.ones((5,5))
print(M*N[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [137]:
NN = np.arange(25).reshape(5,5)
NN[[0,1]] = NN[[1,0]] #swap
print(NN)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [138]:
faces = np.random.randint(0,100,(10,3))
OO = np.roll(faces.repeat(2,axis=1),-1,axis=1)
OO = OO.reshape(len(OO)*3,2)
OO = np.sort(OO,axis=1)

PP = OO.view( dtype=[('p0',OO.dtype),('p1',OO.dtype)] )
PP = np.unique(PP)
print(PP)

[( 2,  2) ( 2, 39) ( 3, 25) ( 3, 93) ( 5, 88) ( 5, 89) ( 9, 83) ( 9, 97)
 (10, 47) (10, 90) (12, 14) (12, 64) (14, 64) (25, 93) (34, 50) (34, 52)
 (45, 49) (45, 91) (47, 90) (49, 91) (50, 52) (50, 91) (50, 95) (75, 77)
 (75, 96) (77, 96) (83, 97) (88, 89) (91, 95)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [139]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [141]:
def averages(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
QQ = np.arange(20)
print(averages(QQ, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [142]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
RR = rolling(np.arange(10), 3)
print(RR)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [144]:
SS = np.random.uniform(-1.0,1.0,100)
print(np.negative(SS, out=SS)) #negate

SS = np.random.randint(0,2,100)
print(np.logical_not(SS, out=SS)) #change sign

[-0.43142588  0.59859061  0.99627396  0.5061813   0.2986948  -0.75969152
  0.09852039  0.87043876  0.13050159 -0.26983961  0.29544981  0.19388506
 -0.88774356  0.84948479  0.12381086 -0.86133151  0.81037492 -0.1238283
 -0.59918499  0.52416698  0.18695595 -0.47251299 -0.92117043 -0.59976303
  0.71169079 -0.2194166  -0.25086565  0.97415259 -0.45587028 -0.0324917
  0.90116924  0.2811058  -0.64532039  0.20115784 -0.69115601  0.14410459
  0.24122662 -0.79970774 -0.76669329  0.818251   -0.59007297  0.70438253
 -0.11152939 -0.27525082  0.54086191  0.1070056  -0.0055339  -0.2172159
 -0.17467491  0.0604967   0.16020891  0.1573619  -0.52369539  0.7920129
 -0.62214378  0.52645377 -0.53538175 -0.23886017  0.36976027  0.50107766
  0.09816686 -0.33300007  0.45323223  0.90179019 -0.61841695  0.43110295
  0.59279946  0.52638756 -0.15583409  0.25777017 -0.86229103  0.18841807
  0.2287678   0.05469322  0.85113725 -0.20106931  0.31634615  0.843137
 -0.8115738   0.94390636  0.58514223 -0.46873879  0.32093

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [153]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
 
print("Distance from p to (PO, P1):", [x for x in distance(P0, P1, p)])

Distance from p to (PO, P1): [1.8313287239123373, 2.5640799000521093, 5.099403702870596, 7.142537274796611, 6.469783494437534, 2.080045169655839, 10.956626653403658, 1.1927409378556184, 5.977329582321501, 4.483721602433141]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [156]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
P = np.random.uniform(-10, 10,(10,2))

print("Distance from p to (PO, P1):", np.array([distance(P0,P1,P_j) for P_j in P]))

Distance from p to (PO, P1): [[ 4.29916349  4.23818085  8.03233455  6.6405848   8.71025014  3.18622955
   3.9033785  10.72694093  1.42601259  0.18769035]
 [12.28269988  7.45993477  0.42597785  1.27891201  0.1327635   2.0244737
   3.20704788 16.55014636  7.53225981  6.51210984]
 [ 2.01866776  8.64473252  6.01658513  3.25237841 11.95744441 14.59577906
   9.39764654  0.01900807 10.21144718  9.82550706]
 [ 6.17706285  2.15642733  3.64946483  1.49487768  5.71967553  3.96273991
   0.06692718 10.42050327  6.60443098  0.29905605]
 [11.4834466   0.34026901  5.30804075  7.48274352  1.33751753  3.28982012
   5.83492792 11.9548802  15.87844125  2.58455606]
 [10.51736023  2.35087248  2.26130727  3.55010431  0.52294888  2.22780331
   2.53278978 12.66719162 11.97610471  2.98268618]
 [ 2.84661972  2.9788588   3.98254353  1.45488219  7.99883084  8.80968331
   4.8587401   5.75330625  9.05341657  4.17680613]
 [12.5804987   4.20244099  3.58830069  3.54171873  1.3445298   0.16274503
   1.34676222 14.773549

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [157]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 4 9 2 3 8 4 0 7 2]
 [1 3 3 8 5 2 3 7 7 4]
 [9 7 0 3 7 7 0 0 1 5]
 [3 8 8 7 3 7 2 5 5 7]
 [5 5 0 3 3 1 3 3 0 7]
 [3 9 8 8 3 8 4 5 1 9]
 [6 7 8 2 7 2 7 8 8 5]
 [7 6 6 5 7 4 0 9 3 6]
 [7 5 4 5 9 4 9 8 3 3]
 [9 4 1 8 3 6 3 6 4 9]]
[[0 0 0 0 0]
 [0 8 4 9 2]
 [0 1 3 3 8]
 [0 9 7 0 3]
 [0 3 8 8 7]]


C:\anaconda\envs\test3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [162]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [166]:
TT = np.random.uniform(0,1,(10,10))
U,S,V = np.linalg.svd(TT)
rank = np.sum(S>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [167]:
UU = np.random.randint(0,10,50)
print(np.bincount(UU).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [168]:
VV = np.random.randint(0,5,(10,10))
n = 3
i = 1+(VV.shape[0]-3)
j = 1+(VV.shape[1]-3)
C = stride_tricks.as_strided(VV, shape=(i,j,n,n), strides=VV.strides+VV.strides)
print(C)

[[[[4 4 0]
   [0 3 0]
   [3 3 0]]

  [[4 0 1]
   [3 0 1]
   [3 0 0]]

  [[0 1 4]
   [0 1 0]
   [0 0 4]]

  [[1 4 2]
   [1 0 3]
   [0 4 4]]

  [[4 2 0]
   [0 3 0]
   [4 4 2]]

  [[2 0 3]
   [3 0 0]
   [4 2 2]]

  [[0 3 3]
   [0 0 0]
   [2 2 0]]

  [[3 3 4]
   [0 0 1]
   [2 0 4]]]


 [[[0 3 0]
   [3 3 0]
   [2 2 4]]

  [[3 0 1]
   [3 0 0]
   [2 4 2]]

  [[0 1 0]
   [0 0 4]
   [4 2 2]]

  [[1 0 3]
   [0 4 4]
   [2 2 3]]

  [[0 3 0]
   [4 4 2]
   [2 3 2]]

  [[3 0 0]
   [4 2 2]
   [3 2 3]]

  [[0 0 0]
   [2 2 0]
   [2 3 1]]

  [[0 0 1]
   [2 0 4]
   [3 1 4]]]


 [[[3 3 0]
   [2 2 4]
   [2 3 1]]

  [[3 0 0]
   [2 4 2]
   [3 1 2]]

  [[0 0 4]
   [4 2 2]
   [1 2 2]]

  [[0 4 4]
   [2 2 3]
   [2 2 4]]

  [[4 4 2]
   [2 3 2]
   [2 4 3]]

  [[4 2 2]
   [3 2 3]
   [4 3 2]]

  [[2 2 0]
   [2 3 1]
   [3 2 2]]

  [[2 0 4]
   [3 1 4]
   [2 2 3]]]


 [[[2 2 4]
   [2 3 1]
   [3 2 1]]

  [[2 4 2]
   [3 1 2]
   [2 1 4]]

  [[4 2 2]
   [1 2 2]
   [1 4 4]]

  [[2 2 3]
   [2 2 4]
   [4 4 3]]

  [[2 3 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [169]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(WW):
    return np.asarray(WW + WW.T - np.diag(WW.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  7  7 11  2]
 [ 7  8  6  4  8]
 [ 7  6  8 42  7]
 [11  4 42  7  8]
 [ 2  8  7  8  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [171]:
p = 10
n = 20

M = np.ones((p,n,n))
V = np.ones((p,n,1))

s = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [172]:
WW = np.ones((16,16))
k = 4
b_s = np.add.reduceat(np.add.reduceat(WW, np.arange(0, WW.shape[0], k), axis=0),
                                          np.arange(0, WW.shape[1], k), axis=1)
print(b_s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [173]:
def iterate(X):
    N = (X[0:-2,0:-2] + X[0:-2,1:-1] + X[0:-2,2:] +
         X[1:-1,0:-2]                + X[1:-1,2:] +
         X[2:  ,0:-2] + X[2:  ,1:-1] + X[2:  ,2:])

    birth = (N==3) & (X[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (X[1:-1,1:-1]==1)
    X[...] = 0
    X[1:-1,1:-1][birth | survive] = 1
    return X

XX = np.random.randint(0,2,(50,50))
for i in range(100): XX = iterate(XX)
print(XX)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [174]:
YY = np.arange(10000)
np.random.shuffle(YY)
n = 5

print(YY[np.argsort(YY)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [175]:
def cartesian_product(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian_product(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [176]:
ZZ = np.array([("Hello", 2.5, 3),
               ("World", 3.6, 2)])
regular= np.core.records.fromarrays(ZZ.T,
                                    names='col1, col2, col3',
                                    formats='S8, f8, i8')
print(regular)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [178]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

4.6 s ± 193 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
557 ms ± 16.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
593 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [179]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
row = np.where(C.any((3,1)).all(1))[0]
print(row)

[0 2 3 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [180]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 2 3]
 [2 1 1]
 [4 4 3]
 [3 3 2]
 [3 3 0]
 [2 0 3]
 [4 4 4]
 [1 4 0]
 [3 1 2]
 [3 3 1]]
[[2 2 3]
 [2 1 1]
 [4 4 3]
 [3 3 2]
 [3 3 0]
 [2 0 3]
 [1 4 0]
 [3 1 2]
 [3 3 1]]
[[2 2 3]
 [2 1 1]
 [4 4 3]
 [3 3 2]
 [3 3 0]
 [2 0 3]
 [1 4 0]
 [3 1 2]
 [3 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [181]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
binary = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(binary[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [182]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [185]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A))
print(np.einsum('i,i->i', A, B))
print(np.einsum('i,i', A, B))
print(np.einsum('i,j->ij', A, B))

4.075983517837068
[0.11852559 0.97144867 0.29852673 0.00153444 0.01007951 0.09154318
 0.02183748 0.05792591 0.31107278 0.07007961]
1.9525738919183642
[[0.11852559 0.22352757 0.08831299 0.01113801 0.03249977 0.04809327
  0.13463387 0.022667   0.07743695 0.22089436]
 [0.51511109 0.97144867 0.3838074  0.04840568 0.14124367 0.2090129
  0.58511752 0.09851057 0.33654025 0.96000479]
 [0.40065518 0.75559613 0.29852673 0.0376501  0.10985981 0.16257095
  0.45510643 0.07662187 0.26176217 0.74669505]
 [0.0163288  0.03079451 0.01216653 0.00153444 0.00447736 0.00662562
  0.01854798 0.00312274 0.01066818 0.03043175]
 [0.03675965 0.06932508 0.02738949 0.00345435 0.01007951 0.0149157
  0.04175549 0.00702997 0.02401638 0.06850842]
 [0.22560763 0.42547372 0.16809943 0.02120065 0.0618617  0.09154318
  0.25626895 0.04314552 0.14739743 0.42046155]
 [0.01922474 0.03625595 0.01432428 0.00180657 0.00527143 0.00780068
  0.02183748 0.00367657 0.0125602  0.03582885]
 [0.30289416 0.57122849 0.22568534 0.02846337 0

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [186]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
X = a*phi*np.cos(phi)
Y = a*phi*np.sin(phi)

dr = (np.diff(X)**2 + np.diff(Y)**2)**.5
r = np.zeros_like(X)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
X_int = np.interp(r_int, r, X)
Y_int = np.interp(r_int, r, Y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [187]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [188]:
X = np.random.randn(100)
N = 1000

ind = np.random.randint(0, X.size, (N, X.size))
means = X[ind].mean(axis=1)
conf = np.percentile(means, [2.5, 97.5])
print(conf)

[-0.1795802   0.19789334]
